### ISSUE TITLE
Actividad 5, Cuadro comparativo, Edgar Fabian Castro Pérez

### ISSUE THREAD

**Issue by 11042002** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-11042002#1]
![1664209195992](https://user-images.githubusercontent.com/72110043/192330243-7b595cac-c813-4c93-9b1d-45c2b7c578da.jpg)
![1664209196005](https://user-images.githubusercontent.com/72110043/192330278-9edb0d63-540b-4296-bc60-22bd2c678bf7.jpg)
![1664209196020](https://user-images.githubusercontent.com/72110043/192330442-9b99d602-4915-447a-8664-5d156cd23579.jpg)
![1664209196033](https://user-images.githubusercontent.com/72110043/192330494-ad617943-46be-46b6-8f2b-30f1badde37c.jpg)
![1664209196056](https://user-images.githubusercontent.com/72110043/192330509-f8849aae-c27c-405d-80ec-0a163e3eb03b.jpg)
![1664209196046](https://user-images.githubusercontent.com/72110043/192330527-7dd54251-dd91-4528-b61e-75cee1fa303c.jpg)

**Comment by Jaczibeth** [comment]
Del 20% obtuviste un 17%
Se tomó en cuenta solo los apartados de características y estructuras ya que solo eso se solicitaba.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
